modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="the_transcendeum"
version="0.1.0"
displayName="The Transcendeum"
credits="Texturers: Sajevius, Aqu, Dylanvhs / Coders: Sajevius / Ideas: everyone from Team Lodestar / Special thanks to MCreator for making this possible!"
displayURL="https://team-lodestar.github.io"
logoFile="logo.png"
authors="Team Lodestar"
description='''
Uncover and venture a new magnificent and  alternate-Overworld dimension transcended beyond normal reality.
'''

[[dependencies.the_transcendeum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




